language: node_js
node_js:
  - "8"

sudo: true

cache:
  directories:
    - "node_modules"

env:
  global:
    - secure: GZYaKTg4FAY166jKQ688k4eqEkRzpyYLoSHQBBoOnwTpK1oLeDKcN6JaAVwI816mmBqagyesB3DfSaJAiB6a4+b/QnXYJm2BcIV1Se+Bof6JgbkCfCBh2qKaoV3OMrClkymw7RTDX+FDWxnH2gd/tixX7cIuHHWmywSOtJa4lmaxfsNG+p85DkZFwP4LAtVYKm7J6QzFHTSHFYl703ImrgMPyLrqYoDNZ/QpVimM5+hB9Q1X/jZza7H7yKk7laBm8b+i4vNNpGi75mbXKLmkoeL44wc55WQEYtrrbJ/1d5Scgwuyx2LpP5O/EhT179FMAfpVQtUqBfsZsQwrLciGLO4PwepykJz9pHNWRSGJcrW8gJVsg0kdw+7R29l3xj9GnFKHCh3ayQ/vm8njbbGPxEDxdMNwLfZ59T0jOHoJzbpSk06+0Vusp+hX4oww9vh1dDrbIr+NhssL+rxUNRH3o6CKhotWVeYOAkxEUQzInZ3NdjA5BQGPUriAJ4U5d2HSPsqAxfL13C+HMJsOwhaUJIGgEh2x4zRhfznAP5ATQEkvLltr3fQHU05SWq+bFjvopmuq1cHvem3Pxoxxo6pWhOBra97yHnqZixGbHtsoNFDXedRzu2/8uV8Bq/uZBdwJqo59ZU2Og9jABOn14HSfi9NIKNTxLs8UmFx11ssiQtw=
    - secure: yxCA/B5/x9iT/Jp/YsgvDCz/KzrRaCjQoW0GtsIeTSx6MYh/k9rDbyfhC163rOZR03RcW7pNlUypSrKzjxfmQERSbKSsnFJ6URFh2mSms2XXEUvy4TPaL8LQni74Qynd16LwjzaFCzt6C572zf4QLGUrw3ZMdQQ3aaXwpzEYAQ/1s1P7danT2aeiF+qOCQlkAlRT4pOK/sKA3UMxKqrd/D3y0M530WotdOKwaGXLuoldbznhRhh6ZWjXcUf7wUeULvX6erCyxAIThxuNF27KB/uzASJm0KZiwUo0BAVXlTGQiUbmy2KQTMUBNGdE4kB+cNl2H78ZfQmfC8pIsqxaqbv9fsGOERtTijDuLDaelJlDl/3bAbz/IWelYDAZcsjh+x/u0+6E2fEO5/dQQngOP5cOn1mrGZsc2TUWeynWUNx9tjHh8JB6OzSTHsdnGqvWZd5RUZwlGEDe/hIouMMd4AospD4niBvB0xFSd4pjcErDIaz+jS5yxwxTRa6w1juaVOnzplNXZy3VbO8vCnwU+8zEvqBZQNC7rRzP+PP6VWgO3rkOsaIR0FgI7soGU6mFxAslGMb/2ZVspna43xkDGIw9IaRST5idkkn4DSeWH0LwTVogSS+idCsqU3JKRBMkdIp8gbYAA/XgH5xIjFXuJLnzk/OUZjiB24bU9arb+JM=

before_script:
  - "ls -alh"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start