language: node_js
node_js:
  - "8"

sudo: true

cache:
  directories:
    - "node_modules"

before_script:
  - "export DISPLAY=:99.0"
  - "export PORT=80"
  - "export PRIVATEPATH=PRIVATE_open"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "npm run serve"
  - sleep 5