language: node_js
node_js:
  - "8"

sudo: true

cache:
  directories:
    - "node_modules"

env:
  global:
    - secure: GZYaKTg4FAY166jKQ688k4eqEkRzpyYLoSHQBBoOnwTpK1oLeDKcN6JaAVwI816mmBqagyesB3DfSaJAiB6a4+b/QnXYJm2BcIV1Se+Bof6JgbkCfCBh2qKaoV3OMrClkymw7RTDX+FDWxnH2gd/tixX7cIuHHWmywSOtJa4lmaxfsNG+p85DkZFwP4LAtVYKm7J6QzFHTSHFYl703ImrgMPyLrqYoDNZ/QpVimM5+hB9Q1X/jZza7H7yKk7laBm8b+i4vNNpGi75mbXKLmkoeL44wc55WQEYtrrbJ/1d5Scgwuyx2LpP5O/EhT179FMAfpVQtUqBfsZsQwrLciGLO4PwepykJz9pHNWRSGJcrW8gJVsg0kdw+7R29l3xj9GnFKHCh3ayQ/vm8njbbGPxEDxdMNwLfZ59T0jOHoJzbpSk06+0Vusp+hX4oww9vh1dDrbIr+NhssL+rxUNRH3o6CKhotWVeYOAkxEUQzInZ3NdjA5BQGPUriAJ4U5d2HSPsqAxfL13C+HMJsOwhaUJIGgEh2x4zRhfznAP5ATQEkvLltr3fQHU05SWq+bFjvopmuq1cHvem3Pxoxxo6pWhOBra97yHnqZixGbHtsoNFDXedRzu2/8uV8Bq/uZBdwJqo59ZU2Og9jABOn14HSfi9NIKNTxLs8UmFx11ssiQtw=
    - secure: yxCA/B5/x9iT/Jp/YsgvDCz/KzrRaCjQoW0GtsIeTSx6MYh/k9rDbyfhC163rOZR03RcW7pNlUypSrKzjxfmQERSbKSsnFJ6URFh2mSms2XXEUvy4TPaL8LQni74Qynd16LwjzaFCzt6C572zf4QLGUrw3ZMdQQ3aaXwpzEYAQ/1s1P7danT2aeiF+qOCQlkAlRT4pOK/sKA3UMxKqrd/D3y0M530WotdOKwaGXLuoldbznhRhh6ZWjXcUf7wUeULvX6erCyxAIThxuNF27KB/uzASJm0KZiwUo0BAVXlTGQiUbmy2KQTMUBNGdE4kB+cNl2H78ZfQmfC8pIsqxaqbv9fsGOERtTijDuLDaelJlDl/3bAbz/IWelYDAZcsjh+x/u0+6E2fEO5/dQQngOP5cOn1mrGZsc2TUWeynWUNx9tjHh8JB6OzSTHsdnGqvWZd5RUZwlGEDe/hIouMMd4AospD4niBvB0xFSd4pjcErDIaz+jS5yxwxTRa6w1juaVOnzplNXZy3VbO8vCnwU+8zEvqBZQNC7rRzP+PP6VWgO3rkOsaIR0FgI7soGU6mFxAslGMb/2ZVspna43xkDGIw9IaRST5idkkn4DSeWH0LwTVogSS+idCsqU3JKRBMkdIp8gbYAA/XgH5xIjFXuJLnzk/OUZjiB24bU9arb+JM=

before_install:
  # sudo apt-get install sftp

before_script:
  - "ls -alh"

  - "ftp -help"
  - "curl -V"
  # - secure: iopLp4r1DaTrgm5sehO9c0DxoQzOE+GeQd3HimWs8UeDYxPMpObyD3irh3nstowUOHC3SrE8lCvW8XzM33OcjdFS98kJYyhHXf1YCgbS65edKNIPLE7M5bJ0y+UriIhT7J0ML0q16LToKuv0bLIMFL8gEgdzaKpiH3HOf5vOrJJrjUdb0K8haIFucPtUc+oQu/Yoy5PgroFbv+3R1Pks5Sc05VlX5pewJGtfxWW86+qoBm9JEBgScr/GGr/K8HVfL7nJT8ZnLQAxLGiCSzJD0yChNQeuvd0wp8ivgif5Zd/f6FcgsbLTo3AvmBejko3LQWzHMbHs8zEozsxlWcE1v2fiNXbovRqwAeObH/BjKJ5/iPsqG3rw+yCeHAkaR94gJIMsQzpZ3LR3nv0Pg9n1yLPCc4aCxcEujZ8Aj+7IPDZmP5rHuZPlUVcwOgMmBoFsghRqXQC+v3LPVcbfiDfcR9V58Bx14JdNGHnX2J2p2A8kEEn120nCgVb9h00VpEW6XtVPSbGsFUL91B9pA7V6vzI+Lhj68jgtUqJry6dLo5ud2C2Y2LYrUoj2PFKCmWwLWR2WqV+wjzpg/QX2EsLaYBsP/WKnnzRhk5l4xJ+xD6sXMnx037kA/U2wFV7vfMDFc9KhBFvdZOLVXkc00OwJ0Fy731oFtlBgeBks15ahawk=
  # - "ls -a"
  # - "quit"

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
